### ISSUE TITLE
got error when tried to run the code

### ISSUE THREAD

**Issue by medozeus** [aub-mind/arabert#138]
```
from transformers import GPT2TokenizerFast, pipeline
#for base and medium
from transformers import GPT2LMHeadModel
#for large and mega
from arabert.aragpt2.grover.modeling_gpt2 import GPT2LMHeadModel

from arabert.preprocess import ArabertPreprocessor

MODEL_NAME='aubmindlab/aragpt2-large'
arabert_prep = ArabertPreprocessor(model_name=MODEL_NAME)




text="فوائد العسل"
text_clean = arabert_prep.preprocess(text)

model = GPT2LMHeadModel.from_pretrained(MODEL_NAME)
tokenizer = GPT2TokenizerFast.from_pretrained(MODEL_NAME) 

generation_pipeline = pipeline("text-generation",model=model,tokenizer=tokenizer)

#feel free to try different decodinn settings
gen_text = generation_pipeline(text_clean,
            pad_token_id=0, # 0 for AraGPT2
            num_beams=5,
            max_length=200,
            top_p=0.95,
            repetition_penalty = 3.0,
            no_repeat_ngram_size = 3)[0]['generated_text']
            
            
print("Prompt:\n",textwrap.fill(text_clean, 200))
print("Generated Text:\n",textwrap.fill(gen_text[len(text_clean):], 200))
```

the error message i got 

`Traceback (most recent call last):
  File "D:\testAI\AI-Blog-Writter-main\AI-Blog-Writter-main\xxxx.py", line 29, in <module>
    gen_text = generation_pipeline(text_clean,
  File "C:\Users\abdulla\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\pipelines.py", line 884, in __call__
    output_sequences = self.model.generate(input_ids=input_ids, **generate_kwargs)  # BS x SL
  File "C:\Users\abdulla\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\abdulla\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\generation_utils.py", line 640, in generate
    return self.beam_sample(
  File "C:\Users\abdulla\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\generation_utils.py", line 1217, in beam_sample
    outputs = self(**model_inputs, return_dict=True)
  File "C:\Users\abdulla\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\testAI\AI-Blog-Writter-main\AI-Blog-Writter-main\arabert\aragpt2\grover\modeling_gpt2.py", line 911, in forward
    return  CausalLMOutputWithCrossAttentions(
TypeError: __init__() got an unexpected keyword argument 'past_key_values'`

**Comment by WissamAntoun** [comment]
Hey, which version of the transformers library you are using?
